sample_filtering:
  sample_list: asdf.txt

probe_filtering:
  mean_detection: 0.01
  rs_probes : true
  ch_probes : true
  snp_targets: 0.1
  cross_reactive: 49
  x_chr: true
  y_chr: false

normalization:
  background_correct: true
  adjust_color_bias: false
  quantile_normalize: true

bmiq:
  seed: 100
  nfit: 50000
  n_cores: 30

phenotype_info:
  phenotype_file: Configs/phenotype_file.txt
  batch_column: artificial_batch
  sample_names_column: ID
  covariates:
    categorical:
      - Gender
      - T2D
      - artificial_categories
    numeric:
      - Purity
      - Cultured_days
      - BMI
      - Hba1c
      - Age_me

analyses:
  -
    method: lm
    covariates: a, b, c
  -
    methold: wilcoxon
    group: g


